name: Sync to Gitee
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Mirror to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/zzq12345
          dst: gitee/zzq12345
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "epg"
          force_update: true
