name: Sync to Gitee
on:
  push:
    branches: [ main ] # 触发分支，根据实际情况修改

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整历史

      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:zzq12345/epg.git"
          destination-repo: "git@gitee.com:zzq12345/epg.git"
