name: Sync to Gitee
on:
  push:
    paths:
      - "epg.xml"  # 仅监听 epg.xml 文件的变更
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Sync to Gitee
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add epg.xml  # 仅添加目标文件
          git commit -m "Sync epg.xml to Gitee"
          git push https://${{ secrets.GITEE_TOKEN }}@gitee.com/zzq12345/epg.git main  # 推送至 Gitee
